dtb-y := \
	exynos7885-jackpotlte_eur_open_03.dtb \
	exynos7885-jackpotlte_eur_open_04.dtb \
	exynos7885-jackpotlte_eur_open_05.dtb \
	exynos7885-jackpotlte_eur_open_06.dtb \
	exynos7885-jackpotlte_eur_open_07.dtb \
	exynos7885-jackpot2lte_eur_open_03.dtb \
	exynos7885-jackpot2lte_eur_open_04.dtb \
	exynos7885-jackpot2lte_eur_open_05.dtb \
	exynos7885-jackpot2lte_eur_open_06.dtb \
	exynos7885-jackpot2lte_eur_open_07.dtb \
	exynos7885-jackpotlte_can_open_03.dtb \
	exynos7885-jackpotlte_can_open_04.dtb \
	exynos7885-jackpotlte_can_open_05.dtb \
	exynos7885-jackpotlte_can_open_06.dtb \
	exynos7885-jackpotlte_can_open_07.dtb \
	exynos7885-jackpotlte_kor_03.dtb \
	exynos7885-jackpotlte_kor_04.dtb \
	exynos7885-jackpotlte_kor_05.dtb \
	exynos7885-jackpotlte_kor_06.dtb \
	exynos7885-jackpotlte_kor_07.dtb \
	exynos7885-a7y18lte_eur_open_00.dtb \
	exynos7885-a7y18lte_eur_open_01.dtb \
	exynos7885-a7y18lte_eur_open_03.dtb \
	exynos7904-m30lte_swa_open_00.dtb \
	exynos7904-m30lte_swa_open_01.dtb \
	exynos7904-m30lte_swa_open_03.dtb \
	exynos7904-m30lte_swa_open_04.dtb \
	exynos7904-m20lte_swa_open_04.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
